### ISSUE TITLE
OrderResponse is always empty

### ISSUE THREAD

**Issue by PRCV1** [stephanstapel/OpenTrans.net#8]
Hello,

I download orders from an FTP folder and have to process them afterwards. However, I have the problem that OrderResponse is always empty.

I load the content of the orders in a MemoryStream and call `OrderResponse.Load(Stream)`.

I have attached a sample file (anonymized) including an image.
I use the latest available version via NuGet in a .NET Core 3.1 class library.

[example.zip](https://github.com/stephanstapel/OpenTrans.net/files/4830036/example.zip)

**Comment by stephanstapel** [comment]
still working on reading order responses. Writing should work though.

**Comment by stephanstapel** [comment]
I have pushed a first version of order response reading. Would be more than happy if you'd try the code that is on github right now.

**Comment by PRCV1** [comment]
Thanks for the quick answer. I assumed that reading would work, because there is a corresponding example in the README.

Then I have to wait until then and parse the files myself.

**Comment by stephanstapel** [comment]
It's in there now. Just not on nuget but in the github repo.

**Comment by PRCV1** [comment]
The reading of the orders works so far wonderfully for me. But I can only try it with eight different orders at the moment

What I'm still missing are the fields `ORDER_ID` and `SUPPLIER_ORDER_ID` from `ORDERRESPONSE_INFO`
Would it be possible to include these fields?

**Comment by stephanstapel** [comment]
that was easy, should all work now
